INSERT INTO topic (id, description, title) VALUES
                                               (1, 'Practice accurate pronunciation of consonants.', 'Korean Consonants'),
                                               (2, 'Common phrases used in daily life.', 'Everyday Conversations'),
                                               (3, 'Sentences frequently used by students at school.', 'School'),
                                               (4, 'Practical expressions for professional settings.', 'Workplace'),
                                               (5, 'Useful expressions when shopping.', 'Shopping'),
                                               (6, 'Essential phrases for traveling.', 'Travel'),
                                               (7, 'Basic sentences for dining at restaurants.', 'Restaurant'),
                                               (8, 'Common expressions used at the hospital.', 'Hospital'),
                                               (9, 'Helpful sentences for banking and finance.', 'Banking'),
                                               (10, 'Useful phrases for using public transportation.', 'Transportation');

INSERT INTO sentence (topic_id, korean, translation, ipa) VALUES
-- Topic 1: Korean Consonants
(1, '가방을 들고 나갔어요', 'I went out carrying a bag.', 'kɐbɐŋɨl dɨl ko nɐgɐʌs͈ ʌjo'),
(1, '나무 아래에서 쉬고 있어요', 'I am resting under the tree.', 'nɐmu ɐɾɛesʌ swi ko it ʌjo'),
(1, '다리가 아파서 쉬어야겠어요', 'My legs hurt, so I should take a break.', 'tɐɾi kɐ ɐpʰɨɐsʌ swiʌjɐ kʲes͈ʌ jo'),
(1, '고양이가 창밖을 바라보고 있어요.', 'The cat is looking out the window.', 'kojɐŋʲi kɐ t͡ɕʰɐŋbɐk͈ɨl bɐɾɐbo ko it ʌjo'),
(1, '노래를 듣는 걸 좋아해요.', 'I like listening to music.', 'noɾɛ ɾɨl dɨt nɨŋ gʌsɨl ɟoɦɐɦɐ ʌjo'),
(1, '달이 밝게 빛나고 있어요.', 'The moon is shining brightly.', 'tɐl i pɐk kʲe pʲinnɐ ko it ʌjo'),
(1, '시계를 차고 있어요.', 'I am wearing a watch.', 'ɕigjeje t͡ɕʰaɡo isʌjo'),
(1, '물고기가 헤엄치고 있어요.', 'The fish is swimming.', 'mulɡoɡiɡa hɛʌmt͡ɕʰiɡo isʌjo'),
(1, '비행기가 하늘을 날고 있어요.', 'The airplane is flying in the sky.', 'pihɛŋɡiɡa hanɯɾɯl nalɡo isʌjo'),
(1, '아기가 웃고 있어요.', 'The baby is smiling.', 'aɡiɡa ut̚ko isʌjo'),

-- Topic 2: Everyday Conversations
(2, '안녕하세요.', 'Hello.', 'ɐnnjʌŋ hɐsejo'),
(2, '좋은 하루 보내세요!', 'Have a good day!', 't͡ɕot ɨn hɐɾu ponɛsejo'),
(2, '지금 몇 시인가요?', 'What time is it now?', 't͡ɕigɨm mjʌt ɕi i kɐjo'),
(2, '오늘 날씨가 참 좋네요!', 'The weather is really nice today!', 'onɨl nɐlɕ͈i kɐ t͡ɕʰɐm t͡ɕonejo'),
(2, '커피 한 잔 주세요.', 'One cup of coffee, please.', 'kʰʌpʰʲi hɐn t͡ɕɐn ɟusejo'),
(2, '이 옷은 얼마인가요?', 'How much is this clothing?', 'i os ɨn ʌlmɐ i kɐjo'),
(2, '잘 지냈어요?', 'How have you been?', 't͡ɕal t͡ɕinɛssʌjo'),
(2, '정말 고마워요.', 'Thank you so much.', 't͡ɕʌŋmal komaʌjo'),
(2, '죄송합니다.', 'I’m sorry.', 't͡ɕʰwe soŋhamnida'),
(2, '괜찮아요.', 'It’s okay.', 'kwɛnʧʰaɦajo'),

-- Topic 3: School
(3, '학교에 가는 길이에요.', 'I am on my way to school.', 'hɐkkʲoe kɐ nɨŋ gʲil iejo'),
(3, '오늘 수업이 몇 시에 시작하나요?', 'What time does class start today?', 'onɨl suʌp i mjʌt ɕie ɕiɟɐkʰɐnɐjo'),
(3, '숙제를 다 끝냈어요.', 'I finished my homework.', 'sukt͡ɕe ɾɨl dɐ k͈ɨnnɛʌs͈ ʌjo'),
(3, '친구들과 도서관에서 공부했어요.', 'I studied with my friends in the library.', 't͡ɕʰiŋgu tɨl kwɐ tssʌkwɐnesʌ koŋbu hɐʌs͈ ʌjo'),
(3, '선생님께 질문이 있어요.', 'I have a question for the teacher.', 'sʌnsɛŋniŋk͈ʲe t͡ɕilmun i it ʌjo'),
(3, '체육 시간에 농구를 했어요.', 'We played basketball during PE class.', 't͡ɕʰejuk ɕigɐne noŋgu ɾɨl hɐʌs͈ ʌjo'),
(3, '시험을 잘 봤어요.', 'I did well on the test.', 'ɕihʌmɯl t͡ɕal pwasʌjo'),
(3, '교실에 들어갔어요.', 'I went into the classroom.', 'kjoɕiɾe tɯɾʌkasʌjo'),
(3, '선생님이 설명해 주셨어요.', 'The teacher explained it.', 'sʌnsɛŋnimi sʌljʌmɦɛ t͡ɕuɕʌssʌjo'),
(3, '친구랑 점심을 먹었어요.', 'I had lunch with my friend.', 't͡ɕʰiŋɡuɾaŋ t͡ɕʌmɕimɯl mʌkʌssʌjo'),

-- Topic 4: Workplace
(4, '출근 시간이 몇 시인가요?', 'What time is the work start time?', 't͡ɕʰulgɨn ɕigɐn i mjʌt ɕi i kɐjo'),
(4, '회의가 곧 시작돼요.', 'The meeting will start soon.', 'hwei kɐ kot ɕiɟɐk twe ʌjo'),
(4, '이 서류를 어디에 제출하면 되나요?', 'Where should I submit this document?', 'i sʌlju ɾɨl ʌdie t͡ɕet͡ɕʰul hɐ mjʌn twenɐjo'),
(4, '업무가 끝나면 연락 주세요.', 'Please contact me when you finish work.', 'ʌmmu kɐ k͈ɨnnɐ mjʌn jʌllɐk t͡ɕusejo'),
(4, '이번 프로젝트의 마감일은 언제인가요?', 'When is the deadline for this project?', 'ibʌm pʰɨɾoɟektʰɨ i mɐgɐm il ɨn ʌnɟe i kɐjo'),
(4, '점심 식사 후 다시 회의실에서 만나요.', 'Let’s meet again in the conference room after lunch.', 't͡ɕʌmɕim ɕiksɐ hu tɐɕi hweiɕiɾesʌ mɐn nɐ i jo'),
(4, '회의가 길어졌어요.', 'The meeting ran long.', 'hweiɡa kiɾʌd͡ʑʌssʌjo'),
(4, '보고서를 작성했어요.', 'I wrote the report.', 'poɡosʌɾɯl t͡ɕaksʌŋhɛssʌjo'),
(4, '메일을 확인했어요.', 'I checked the email.', 'meiruɾɯl hwaɡinhɛssʌjo'),
(4, '회의실 예약을 했어요.', 'I reserved the meeting room.', 'hweiɕiɾ jɛjakɯɾɯl hɛssʌjo'),

-- Topic 5: Shopping
(5, '이거 얼마예요?', 'How much is this?', 'igo ʌlma jɛjo'),
(5, '다른 색깔 있어요?', 'Do you have a different color?', 'taɾɨn sɛk͈al isʌjo'),
(5, '이거 입어봐도 돼요?', 'Can I try this on?', 'igo ibʌbwa do twɛjo'),
(5, '카드로 결제할게요.', 'I’ll pay by card.', 'kʰadu ɾo kjʌlt͡ɕɛ hal kɛjo'),
(5, '현금으로 할게요.', 'I’ll pay in cash.', 'hjʌnɡɯm ɯɾo hal kɛjo'),
(5, '영수증 주세요.', 'Please give me a receipt.', 'jʌŋsud͡ʑɯŋ t͡ɕusejo'),
(5, '환불 가능한가요?', 'Can I get a refund?', 'hwanbul kanɯnɐn kajo'),
(5, '교환할 수 있나요?', 'Can I exchange this?', 'kjoʍan hal su inajo'),
(5, '세일 중인가요?', 'Is this on sale?', 'sɛil t͡ɕuŋ inajo'),
(5, '더 큰 사이즈 있어요?', 'Do you have a bigger size?', 'tʌ kɯn saidzɯ isʌjo'),

-- Topic 6: Travel
(6, '비행기는 몇 시에 출발해요?', 'What time does the flight depart?', 'pi hɛŋɡi nɯn mjʌt ɕie t͡ɕʰulbal hɛjo'),
(6, '호텔까지 어떻게 가요?', 'How do I get to the hotel?', 'hotʰɛl kkad͡ʑi ʌttʌkʰe kayo'),
(6, '예약했어요.', 'I have a reservation.', 'jejak hɛssʌjo'),
(6, '여권을 보여주세요.', 'Please show your passport.', 'jʌkwʌn ɯl pojʌ t͡ɕusejo'),
(6, '수하물은 어디서 찾나요?', 'Where do I claim my baggage?', 'suhamurɯn ʌdʌsʌ t͡ɕʰannajo'),
(6, '관광 안내소는 어디에 있어요?', 'Where is the tourist info center?', 'kwanɡwanɡ anɛso nɯn ʌdi e isʌjo'),
(6, '여기는 어디인가요?', 'Where is this?', 'jʌginɯn ʌdi inajo'),
(6, '사진 찍어주세요.', 'Please take a photo.', 'sad͡ʑin t͡ɕ͈ikʌ t͡ɕusejo'),
(6, '여행은 즐거웠어요.', 'The trip was enjoyable.', 'jʌhɛŋ ɯn t͡ɕɯlgʌwʌssʌjo'),
(6, '입국 신고서를 작성해주세요.', 'Please fill out the entry form.', 'ipkuk ɕiŋɡosʌɾɯl t͡ɕak͈sʌŋ hɛ t͡ɕusejo'),

-- Topic 7: Restaurant
(7, '메뉴 좀 볼 수 있을까요?', 'Can I see the menu?', 'menju t͡ɕom bol su isɯlkkajo'),
(7, '추천 메뉴 있어요?', 'Do you have any recommendations?', 't͡ɕʰut͡ɕʰʌn menju isʌjo'),
(7, '이거 하나 주세요.', 'Please give me one of this.', 'igo hɐna t͡ɕusejo'),
(7, '매운 음식 있어요?', 'Do you have spicy food?', 'mɛun ɯmsik isʌjo'),
(7, '덜 맵게 해주세요.', 'Please make it less spicy.', 'tʌl mɛp ke hɛ t͡ɕusejo'),
(7, '물 좀 주세요.', 'Please give me some water.', 'mul t͡ɕom t͡ɕusejo'),
(7, '포장해 주세요.', 'Please pack it to go.', 'pʰod͡ʑaŋ hɛ t͡ɕusejo'),
(7, '계산서 주세요.', 'Please give me the bill.', 'kesɐnsʌ t͡ɕusejo'),
(7, '이건 뭐예요?', 'What is this?', 'iɡʌn mwo jɛjo'),
(7, '맛있게 먹었습니다.', 'It was delicious.', 'masit͡ske mʌɡʌssɯmnita'),

-- Topic 8: Hospital
(8, '어디 아프세요?', 'Where does it hurt?', 'ʌdi apʰɯsejo'),
(8, '열이 있어요.', 'I have a fever.', 'jʌɾi isʌjo'),
(8, '두통이 심해요.', 'I have a severe headache.', 'tutʰoŋi ɕimɛjo'),
(8, '약 처방해 주세요.', 'Please prescribe medicine.', 'jak t͡ɕʰʌbaŋ hɛ t͡ɕusejo'),
(8, '감기에 걸렸어요.', 'I caught a cold.', 'kamgi e kʌljʌssʌjo'),
(8, '소화가 잘 안돼요.', 'I have indigestion.', 'sohwa ga t͡ɕal ɐntwɛjo'),
(8, '배탈이 났어요.', 'I have a stomachache.', 'bɛtʰaɾi nɐssʌjo'),
(8, '주사를 맞았어요.', 'I got a shot.', 't͡ɕusʰaɾɯl mat͡ɕʰassʌjo'),
(8, '입원해야 하나요?', 'Do I need to be hospitalized?', 'ipwʌn hɛja hanajo'),
(8, '다음 진료는 언제예요?', 'When is the next appointment?', 'taɯm t͡ɕinɾjo nɯn ʌnd͡ʑɛ jɛjo'),

-- Topic 9: Banking
(9, '계좌를 개설하고 싶어요.', 'I want to open an account.', 'ked͡ʑwa ɾɯl kɛsʌl hako ɕiphʌjo'),
(9, '입금하고 싶어요.', 'I want to deposit money.', 'ipkɯm hako ɕiphʌjo'),
(9, '출금하려고 왔어요.', 'I’m here to withdraw money.', 't͡ɕʰulgɯm haɾʌɡo wassʌjo'),
(9, '통장 정리해주세요.', 'Please update my passbook.', 'tʰoŋd͡ʑaŋ t͡ɕʌŋni hɛ t͡ɕusejo'),
(9, '인터넷 뱅킹 신청하고 싶어요.', 'I want to apply for internet banking.', 'intʰʌnɛt bɛŋkʰiŋ ɕint͡ɕʰʌŋ hako ɕiphʌjo'),
(9, '비밀번호를 잊어버렸어요.', 'I forgot my password.', 'pimilhʌnɯɾɯl id͡ʑʌbʌɾjʌssʌjo'),
(9, '환전하고 싶어요.', 'I want to exchange currency.', 'hwand͡ʑʌn hako ɕiphʌjo'),
(9, '외화 계좌 있어요?', 'Do you have a foreign currency account?', 'wɛhwa ked͡ʑwa isʌjo'),
(9, '잔액이 얼마예요?', 'What’s the balance?', 't͡ɕanɛk i ʌlma jɛjo'),
(9, '송금해 주세요.', 'Please send the money.', 'soŋgɯm hɛ t͡ɕusejo'),

-- Topic 10: Transportation
(10, '버스는 어디에서 타요?', 'Where do I take the bus?', 'bʌsɯ nɯn ʌdiesʌ tʰajo'),
(10, '지하철역이 어디예요?', 'Where is the subway station?', 't͡ɕiha t͡ɕʰʌl jʌki ʌdijejo'),
(10, '교통카드 있어요?', 'Do you have a transportation card?', 'kjo tʰoŋ kʰadɯ isʌjo'),
(10, '몇 번 버스를 타야 해요?', 'Which bus number should I take?', 'mjʌt pʌn bʌsɯɾɯl tʰaja hɛjo'),
(10, '이 지하철은 어디로 가요?', 'Where does this subway go?', 'i t͡ɕi hɐ t͡ɕʰʌl ɯn ʌdi ɾo kayo'),
(10, '표는 어디서 사요?', 'Where do I buy a ticket?', 'pʰjo nɯn ʌdʌsʌ sajo'),
(10, '이건 종점이에요.', 'This is the last stop.', 'igon t͡ɕoŋd͡ʑʌm i ejo'),
(10, '갈아타야 하나요?', 'Do I need to transfer?', 'kaɾa tʰaja hanajo'),
(10, '운전기사님, 여기서 내려주세요.', 'Driver, please drop me off here.', 'unjʌn ɡisanim, jʌɡisʌ nɛɾjʌ t͡ɕusejo'),
(10, '다음 정류장은 어디인가요?', 'Where is the next stop?', 'taɯm t͡ɕʌŋnju d͡ʑaŋ ɯn ʌndi inajo');